services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pzkosz-postgres:5432/pzkosz
      SPRING_DATASOURCE_USERNAME: pzkosz_user
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - pzkosz-net
    depends_on:
      - pzkosz-postgres

  pzkosz-postgres:
    image: postgres
    environment:
      POSTGRES_DB: pzkosz
      POSTGRES_USER: pzkosz_user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    networks:
      - pzkosz-net
    volumes:
      - pzkosz-db-data:/var/lib/postgresql/data

networks:
  pzkosz-net:
    driver: bridge

volumes:
  pzkosz-db-data:
